### ISSUE TITLE
Do/Did you have a Git server?

### ISSUE THREAD

**Issue by ghost** [CarmJos/CarmJos#8]
Hello CarmJos!

This is NorthRealm on Github. I am searching for some source and have discovered `git.carm.cc` through Google. I assume in the site there would be something I am in need of. However, I cannot access it properly, saying access denied. Is/Was `git.carm.cc` your site? I would like to explore it deeper.

In addition, if applicable, I would like to keep conversation in private via Email, Discord or any other approach. Waiting for your earliest reply!

Regards,
NorthRealm

**Comment by CarmJos** [comment]
Hi, NorthRealm.

I do have a Git server before, but now i have ended the service for the users that not lived in China.

My Git service is just a mirror of my github projects(including `CarmJos` and `carm-outsource`). You can simply using github to view my projects, instead of using my Git.

Regards,
Carm.

**Comment by ghost** [comment]
Thanks for clarification. Unfortunately I have looked around and found no source I am looking for. Do you still have a copy of the project as shown in the picture?
![4](https://github.com/user-attachments/assets/31a50805-a4ad-48a2-aaed-caa5f5537a7b)

**Comment by CarmJos** [comment]
> Thanks for clarification. Unfortunately I have looked around and found no source I am looking for. Do you still have a copy of the project as shown in the picture? ![4](https://private-user-images.githubusercontent.com/155140859/397943275-31a50805-a4ad-48a2-aaed-caa5f5537a7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDI2NjAsIm5iZiI6MTczNDgwMjM2MCwicGF0aCI6Ii8xNTUxNDA4NTkvMzk3OTQzMjc1LTMxYTUwODA1LWE0YWQtNDhhMi1hYWVkLWNhYTVmNTUzN2E3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxNzMyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYWI0NzU2ZDY3OWIzYmZlOGI3Mjg1ZTg4MDExZTY3ODhiZWVmZGRkOWQ1MzhiYjFmZDU0YzRmMTQwYzAzZGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.alJB2SAktmls3DYXDijacZLAbFCcAUSUen-dHGh0aJQ)

My git didn't have this project.

**Comment by Ghost-chu** [comment]
> Thanks for clarification. Unfortunately I have looked around and found no source I am looking for. Do you still have a copy of the project as shown in the picture? ![4](https://private-user-images.githubusercontent.com/155140859/397943275-31a50805-a4ad-48a2-aaed-caa5f5537a7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDk5NzIsIm5iZiI6MTczNDgwOTY3MiwicGF0aCI6Ii8xNTUxNDA4NTkvMzk3OTQzMjc1LTMxYTUwODA1LWE0YWQtNDhhMi1hYWVkLWNhYTVmNTUzN2E3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxOTM0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDMxM2EyYmY1NjY2YWIwNjA2M2E3YjVjN2I0MmQ3YTE3YTczYWY5OGI1ZDk4ZDFiMDlmYTZkMTViOWQyNzA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QrQwO5P3UF-V-VG4eZws8S776Ac_QxV1LdRWACpzVvM)

Mineplex used to release them, then quickly deleted and DMCA'd all public repositories.
Unfortunately it's against copyright and the law to share these resources,, no one here (Github) can share these things with you. github is obviously not the place to post and seek out these resources... I don't think we should abuse Github.

–––


On a side note, I see you posted a mod for SocksProxyClient, that's cool, I've wanted to make a mod like that for a while but I've never completely solved the problem in Netty so that I no longer need to open up my proxy tool in TUN mode when I'm touring MP or HY...
I guess I could talk a lot on Mod and Bukkit Plugin, but unfortunately you didn't leave a contact info in either your Github profile or Discord for me to establish contact. So if you'd like, please send an email to ghostchu@qq.com with your Github username and I'd be happy to talk to you in terms of overcoming technical difficulties and data retrieval. I have a collection of technical articles on Socks5 and Netty, and have built some mods for modern versions of Minecraft that I'd be happy to send you for research purposes.
I'd be happy to send them to you for research purposes, but they're just too big, and they're from a project I did a long time ago, I mean, they're too big. Even compressed they are several GB.

**Comment by ghost** [comment]
Hi @Ghost-chu !
Mineplex were once infamous, reputation wasted by themselves. As such, there would be always seekers for **leaked** materials lost in cyber historical trashbins, for whatever purpose, entertainment, research or development.

Thanks for the interest. I will reach you via both email and Discord sooner or later.

**Comment by Ghost-chu** [comment]
> Hi @Ghost-chu ! Mineplex were once infamous, reputation wasted by themselves. As such, there would be always seekers for **leaked** materials lost in cyber historical trashbins, for whatever purpose, entertainment, research or development.
> 
> Thanks for the interest. I will reach you via both email and Discord sooner or later.

Ihave sent those files to a mod called rerere in your server however idk if this person is you but you guys in same DC server. I comment in chat to forward those files to you which include my packet-captured materials and some screen records which when I look into the Netty. Huhhh everything is strange and I take a step on DOH supports but I dont get more steps. Network tech is most strange on this world...

Anyway it's most likely offtopic under this issue so lets move forward to DC.
